#!/usr/bin/env python3
import subprocess
import os
os.chdir("build")

build = subprocess.run(["ninja"], stdout=subprocess.DEVNULL,
  stderr=subprocess.DEVNULL)

if build.returncode == 0:
    print("Built!\n")
else:
    print("Failed to build!\n")


output = subprocess.run(["bin/worms"], shell=True)
print("Completed with status:",output.returncode)
