#!/usr/bin/env python3
import subprocess
import os
import sys
os.chdir("build")

build = subprocess.run(["meson", "compile"], stdout=subprocess.PIPE,
  stderr=subprocess.PIPE)



os.chdir("..")
if build.returncode == 0:
    print("Built!\n")
else:
    print("Failed to build!\n")
    print(build.stdout.decode("utf-8"))
    os._exit(1)

if len(sys.argv) == 1:
    output = subprocess.run(["build/worms"], shell=True)
    print("Completed with status:",output.returncode)
else:
    if sys.argv[1] == "wr":
        output = subprocess.run(["build/worms_wr"]+sys.argv[2:])
        print("Completed with status:",output.returncode)
    if sys.argv[1] == "vm":
        output = subprocess.run(["build/worms"], shell=True)
        print("Completed with status:",output.returncode)

